### ISSUE TITLE
Arabic Target Language code results in wrong language

### ISSUE THREAD

**Issue by R-Sharafaldin** [furfy/polywoof#2]
Hello!

Anytime I try to select the Target Language using DeepL backend to "ar", it just sets itself to Bulgarian.

![image](https://github.com/user-attachments/assets/9f9d6457-55f6-4220-b1bc-5fc3d91a326c)

I found this odd and decided to investigate a bit and it turns out that "az" for Azerbaijani set it to Brazilian.

From what i can gather it looks for the first supported language containing "ar" which happens alphabetically to be Bulgarian and Brazilian for "az".
This makes sense for Azerbaijani as it is not supported by DeepL, but Arabic is supported yet has the same behaviour.

**Comment by furfy** [comment]
There are many ways to type in the desired language, for example: `ar`, `arab`, `arabic`.
I'm pretty sure one of those will work nicely, sorry for the late response!
